import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

// Existing OpenCode IconName -> Lucide asset. Unmapped names keep the hand-drawn set.
const lucideByName: Record<string, string> = {
  "align-right": "align-right",
  "arrow-up": "arrow-up",
  "arrow-up-bold": "arrow-up",
  "arrow-left": "arrow-left",
  "arrow-right": "arrow-right",
  "arrow-sync": "refresh-cw",
  archive: "archive",
  "bell-off": "bell-off",
  "bubble-5": "message-circle",
  prompt: "message-square",
  book: "book",
  brain: "brain",
  robot: "bot",
  fork: "git-fork",
  "bullet-list": "list",
  "check-small": "check",
  play: "play",
  "chevron-down": "chevron-down",
  "chevron-left": "chevron-left",
  "chevron-right": "chevron-right",
  "chevron-grabber-vertical": "grip-vertical",
  "chevron-double-right": "chevrons-right",
  "circle-x": "circle-x",
  close: "x",
  "close-small": "x",
  checklist: "list-checks",
  clock: "clock",
  console: "square-terminal",
  terminal: "square-terminal",
  "terminal-active": "square-terminal",
  review: "newspaper",
  read: "file-text",
  "review-active": "newspaper",
  expand: "maximize-2",
  "expand-corners": "maximize",
  collapse: "minimize-2",
  code: "code",
  "code-lines": "code",
  "circle-ban-sign": "ban",
  "edit-small-2": "pencil",
  eye: "eye",
  enter: "corner-down-left",
  file: "file",
  folder: "folder",
  "file-tree": "folder-tree",
  "tree-nodes": "network",
  "file-tree-active": "folder-tree",
  "magnifying-glass": "search",
  "plus-small": "plus",
  plus: "plus",
  "new-session": "square-plus",
  "new-session-active": "square-plus",
  "pencil-line": "pencil-line",
  mcp: "plug-2",
  glasses: "glasses",
  "magnifying-glass-menu": "search",
  "window-cursor": "mouse-pointer",
  task: "square-check",
  stop: "square",
  status: "rows-3",
  "status-active": "rows-3",
  sidebar: "panel-left",
  "sidebar-active": "panel-left",
  "layout-left": "panel-left",
  "layout-left-partial": "panel-left",
  "layout-left-full": "panel-left",
  "layout-right": "panel-right",
  "layout-right-partial": "panel-right",
  "layout-right-full": "panel-right",
  "layout-bottom": "panel-bottom",
  "layout-bottom-partial": "panel-bottom",
  "layout-bottom-full": "panel-bottom",
  "square-arrow-top-right": "external-link",
  "open-file": "external-link",
  "speech-bubble": "message-circle",
  comment: "message-square",
  "folder-add-left": "folder-plus",
  "dot-grid": "ellipsis",
  "circle-check": "circle-check",
  copy: "copy",
  check: "check",
  photo: "image",
  share: "share",
  shield: "shield",
  download: "download",
  "shopping-bag": "shopping-bag",
  menu: "menu",
  server: "server",
  save: "save",
  branch: "git-branch",
  edit: "pencil",
  help: "circle-help",
  "settings-gear": "settings",
  dash: "minus",
  "cloud-upload": "cloud-upload",
  trash: "trash-2",
  sliders: "sliders-horizontal",
  keyboard: "keyboard",
  selector: "chevrons-up-down",
  "arrow-down-to-line": "arrow-down-to-line",
  warning: "triangle-alert",
  reset: "undo-2",
  refresh: "refresh-cw",
  "refresh-small": "refresh-cw",
  link: "link",
  providers: "layout-grid",
  models: "sparkles",
  "sticky-note": "sticky-note",
}

const here = dirname(fileURLToPath(import.meta.url))
const packageRoot = join(here, "..")
const assetRoots = [
  join(packageRoot, "node_modules/lucide-static/icons"),
  join(packageRoot, "../../node_modules/lucide-static/icons"),
  join(packageRoot, "../../node_modules/.bun/lucide-static@1.31.0/node_modules/lucide-static/icons"),
]

function assetDir() {
  for (const root of assetRoots) {
    if (existsSync(root)) return root
  }
  throw new Error("Could not find lucide-static icons")
}

function innerSvg(svg: string) {
  return svg
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<\?xml[^>]*>/, "")
    .trim()
    .replace(/^<svg[\s\S]*?>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/\n\s*/g, "")
    .trim()
}

const missing: string[] = []
const dir = assetDir()
const entries = Object.entries(lucideByName)
  .map(([name, file]) => {
    const path = join(dir, `${file}.svg`)
    if (!existsSync(path)) {
      missing.push(`${name} -> ${path}`)
      return undefined
    }
    return [name, innerSvg(readFileSync(path, "utf8"))] as const
  })
  .filter((item): item is readonly [string, string] => !!item)

if (missing.length) {
  throw new Error(`Missing Lucide assets:\n${missing.join("\n")}`)
}

const body = `// Generated by packages/ui/script/sync-lucide-icons.ts
// Do not edit by hand.

export const LUCIDE_VIEWBOX = "0 0 24 24"

export const lucideIcons: Partial<Record<string, string>> = {
${entries.map(([name, svg]) => `  ${JSON.stringify(name)}: ${JSON.stringify(svg)},`).join("\n")}
}
`

const out = join(packageRoot, "src/components/lucide-icons.ts")
writeFileSync(out, body)
console.log(`wrote ${entries.length} lucide icons to ${out}`)
