// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	killSidecar: () => __TAURI_INVOKE<void>("kill_sidecar"),
	reloadSidecar: () => __TAURI_INVOKE<null>("reload_sidecar"),
	syncOpenclawServer: () => __TAURI_INVOKE<{
	url: string,
	username: string | null,
	password: string | null,
} | null>("sync_openclaw_server"),
	installCli: () => __TAURI_INVOKE<string>("install_cli"),
	awaitInitialization: (events: Channel) => __TAURI_INVOKE<{
	url: string,
	username: string | null,
	password: string | null,
} | null>("await_initialization", { events }),
	recordStartupProfile: (origin: string, phase: string, detail: string | null, frontendElapsedMs: number | null) => __TAURI_INVOKE<void>("record_startup_profile", { origin, phase, detail, frontendElapsedMs }),
	listStartupProfile: () => __TAURI_INVOKE<StartupSample[]>("list_startup_profile"),
	getDefaultServerUrl: () => __TAURI_INVOKE<string | null>("get_default_server_url"),
	setDefaultServerUrl: (url: string | null) => __TAURI_INVOKE<null>("set_default_server_url", { url }),
	getWslConfig: () => __TAURI_INVOKE<WslConfig>("get_wsl_config"),
	setWslConfig: (config: WslConfig) => __TAURI_INVOKE<null>("set_wsl_config", { config }),
	getOpenclawConfig: () => __TAURI_INVOKE<OpenclawConfig>("get_openclaw_config"),
	setOpenclawConfig: (config: OpenclawConfig) => __TAURI_INVOKE<null>("set_openclaw_config", { config }),
	getDisplayBackend: () => __TAURI_INVOKE<"wayland" | "auto" | null>("get_display_backend"),
	setDisplayBackend: (backend: LinuxDisplayBackend) => __TAURI_INVOKE<null>("set_display_backend", { backend }),
	getOpenclawServer: () => __TAURI_INVOKE<{
	url: string,
	username: string | null,
	password: string | null,
} | null>("get_openclaw_server"),
	testOpenclawServer: (config: OpenclawConfig) => __TAURI_INVOKE<OpenclawTestResult>("test_openclaw_server", { config }),
	abortOpenclawTest: () => __TAURI_INVOKE<boolean>("abort_openclaw_test"),
	syncHermesServer: () => __TAURI_INVOKE<{
	url: string,
	username: string | null,
	password: string | null,
} | null>("sync_hermes_server"),
	getHermesConfig: () => __TAURI_INVOKE<HermesConfig>("get_hermes_config"),
	setHermesConfig: (config: HermesConfig) => __TAURI_INVOKE<null>("set_hermes_config", { config }),
	getHermesServer: () => __TAURI_INVOKE<{
	url: string,
	username: string | null,
	password: string | null,
} | null>("get_hermes_server"),
	testHermesServer: (config: HermesConfig) => __TAURI_INVOKE<HermesTestResult>("test_hermes_server", { config }),
	abortHermesTest: () => __TAURI_INVOKE<boolean>("abort_hermes_test"),
	syncGenericagentServer: () => __TAURI_INVOKE<{
	url: string,
	username: string | null,
	password: string | null,
} | null>("sync_genericagent_server"),
	getGenericagentConfig: () => __TAURI_INVOKE<GenericagentConfig>("get_genericagent_config"),
	setGenericagentConfig: (config: GenericagentConfig) => __TAURI_INVOKE<null>("set_genericagent_config", { config }),
	getGenericagentServer: () => __TAURI_INVOKE<{
	url: string,
	username: string | null,
	password: string | null,
} | null>("get_genericagent_server"),
	testGenericagentServer: (config: GenericagentConfig) => __TAURI_INVOKE<GenericagentTestResult>("test_genericagent_server", { config }),
	abortGenericagentTest: () => __TAURI_INVOKE<boolean>("abort_genericagent_test"),
	parseMarkdownCommand: (markdown: string) => __TAURI_INVOKE<string>("parse_markdown_command", { markdown }),
	checkAppExists: (appName: string) => __TAURI_INVOKE<boolean>("check_app_exists", { appName }),
	filterDirectories: (paths: string[]) => __TAURI_INVOKE<string[]>("filter_directories", { paths }),
	openInFinder: (path: string) => __TAURI_INVOKE<null>("open_in_finder", { path }),
	openInVscode: (path: string) => __TAURI_INVOKE<null>("open_in_vscode", { path }),
	openInEditor: (editor: string, path: string, customPath: string | null) => __TAURI_INVOKE<null>("open_in_editor", { editor, path, customPath }),
	getCustomEditorPath: () => __TAURI_INVOKE<string | null>("get_custom_editor_path"),
	setCustomEditorPath: (path: string | null) => __TAURI_INVOKE<null>("set_custom_editor_path", { path }),
	getDefaultEditor: () => __TAURI_INVOKE<string | null>("get_default_editor"),
	setDefaultEditor: (editor: string | null) => __TAURI_INVOKE<null>("set_default_editor", { editor }),
	listConfigFiles: (directory: string | null) => __TAURI_INVOKE<ConfigFile[]>("list_config_files", { directory }),
	listTrellisTasks: (directory: string) => __TAURI_INVOKE<TrellisTaskList>("list_trellis_tasks", { directory }),
	setTrellisCurrentTask: (path: string) => __TAURI_INVOKE<null>("set_trellis_current_task", { path }),
	archiveTrellisTask: (path: string) => __TAURI_INVOKE<null>("archive_trellis_task", { path }),
	getConfigWorkspace: () => __TAURI_INVOKE<ConfigWorkspace>("get_config_workspace"),
	listConfigDirectory: (path: string) => __TAURI_INVOKE<ConfigTreeItem[]>("list_config_directory", { path }),
	readConfigFile: (path: string) => __TAURI_INVOKE<string | null>("read_config_file", { path }),
	writeConfigFile: (path: string, content: string) => __TAURI_INVOKE<null>("write_config_file", { path, content }),
	createConfigFile: (path: string, content: string) => __TAURI_INVOKE<null>("create_config_file", { path, content }),
	wslPath: (path: string, mode: "windows" | "linux" | null) => __TAURI_INVOKE<string>("wsl_path", { path, mode }),
	resolveAppPath: (appName: string) => __TAURI_INVOKE<string | null>("resolve_app_path", { appName }),
	openPath: (path: string, appName: string | null) => __TAURI_INVOKE<null>("open_path", { path, appName }),
};

/** Events */
export const events = {
	sqliteMigrationProgress: makeEvent<SqliteMigrationProgress>("sqlite-migration-progress"),
};

/* Types */
export type ConfigFile = {
		id: string,
		label: string,
		path: string,
		exists: boolean,
		scope: string,
		kind: string,
	};

export type ConfigTreeItem = {
		path: string,
		kind: string,
	};

export type ConfigWorkspace = {
		configRoot: string | null,
		agentsRoot: string | null,
		skillsRoot: string | null,
		pluginsRoot: string | null,
		agentsMdPath: string | null,
		agents: ConfigWorkspaceFile[],
		plugins: ConfigWorkspaceFile[],
	};

export type ConfigWorkspaceFile = {
		name: string,
		path: string,
		kind: string,
	};

export type GenericagentConfig = {
		enabled: boolean,
		pythonExecutable: string | null,
		genericAgentDir: string | null,
	};

export type GenericagentTestResult = {
		ok: boolean,
		logs: string[],
	};

export type HermesConfig = {
		enabled: boolean,
		pythonExecutable: string | null,
		hermesDir: string | null,
		hermesHome: string | null,
	};

export type HermesTestResult = {
		ok: boolean,
		logs: string[],
	};

export type InitStep = { phase: "server_waiting" } | { phase: "sqlite_waiting" } | { phase: "done" } | { phase: "failed"; detail: string };

export type LinuxDisplayBackend = "wayland" | "auto";

export type OpenclawConfig = {
		enabled: boolean,
		url: string | null,
		token: string | null,
	};

export type OpenclawTestResult = {
		ok: boolean,
		logs: string[],
	};

export type ServerReadyData = {
		url: string,
		username: string | null,
		password: string | null,
	};

export type SqliteMigrationProgress = { type: "InProgress"; value: number } | { type: "Done" };

export type StartupSample = {
		origin: string,
		phase: string,
		nativeElapsedMs: number,
		deltaMs: number,
		frontendElapsedMs: number | null,
		detail: string | null,
	};

export type TrellisTask = {
		id: string,
		name: string,
		title: string,
		status: string,
		priority: string | null,
		assignee: string | null,
		package: string | null,
		parent: string | null,
		children: string[],
		createdAt: string | null,
		completedAt: string | null,
		path: string,
		worktreeRoot: string,
		worktreeName: string,
		current: boolean,
	};

export type TrellisTaskList = {
		root: string,
		current: string | null,
		skipped: number,
		tasks: TrellisTask[],
	};

export type WslConfig = {
		enabled: boolean,
	};

export type WslPathMode = "windows" | "linux";

/* Tauri Specta runtime */
function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: (payload: T) => __TAURI_EVENT.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: (payload: T) => target.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}
