// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core"

/** Commands */
export const commands = {
	killSidecar: () => __TAURI_INVOKE<void>("kill_sidecar"),
	installCli: () => __TAURI_INVOKE<string>("install_cli"),
	ensureServerReady: () => __TAURI_INVOKE<ServerReadyData>("ensure_server_ready"),
	getDefaultServerUrl: () => __TAURI_INVOKE<string | null>("get_default_server_url"),
	setDefaultServerUrl: (url: string | null) => __TAURI_INVOKE<null>("set_default_server_url", { url }),
	parseMarkdownCommand: (markdown: string) => __TAURI_INVOKE<string>("parse_markdown_command", { markdown }),
	openInFinder: (path: string) => __TAURI_INVOKE<null>("open_in_finder", { path }),
	openInVscode: (path: string) => __TAURI_INVOKE<null>("open_in_vscode", { path }),
	openInEditor: (editor: string, path: string, customPath: string | null) =>
		__TAURI_INVOKE<null>("open_in_editor", { editor, path, customPath }),
	getCustomEditorPath: () => __TAURI_INVOKE<string | null>("get_custom_editor_path"),
	setCustomEditorPath: (path: string | null) => __TAURI_INVOKE<null>("set_custom_editor_path", { path }),
	getDefaultEditor: () => __TAURI_INVOKE<string | null>("get_default_editor"),
	setDefaultEditor: (editor: string | null) => __TAURI_INVOKE<null>("set_default_editor", { editor }),
}

/* Types */
export type ServerReadyData = {
		url: string,
		password: string | null,
	};

