import { Index, Show, createEffect, createMemo, createSignal, onCleanup, onMount, untrack } from "solid-js"
import { IconButton } from "@opencode-ai/ui/icon-button"
import { Icon } from "@opencode-ai/ui/icon"
import { Spinner } from "@opencode-ai/ui/spinner"
import { useLanguage } from "@/context/language"
import { useSessionLayout } from "@/pages/session/session-layout"

// P1-A-01: right-sidebar embedded browser panel (desktop only), docked in the
// session side panel next to the review panel and file preview. The visible
// page is a native WebContentsView owned by the desktop main process; this
// component renders the chrome (address bar) plus a transparent placeholder
// whose bounds are mirrored to the native view over IPC.
//
// Multi-tab (2026-09-29): the user's own tab (persist:browse) coexists with
// agent-driven tabs (agent-browser-<sessionID>) created by the browser_* tools.
// Agent tabs are marked with the brand accent; the panel mirrors bounds to the
// active tab's partition only, so exactly one WebContentsView is visible.

export const BROWSER_PARTITION = "persist:browse"
// Must match agentPartition() in packages/desktop/src/main/browser.ts and
// packages/opencode/src/browser/index.ts (kept in sync by convention — no
// shared package spans desktop+server+app).
export const AGENT_PARTITION_PREFIX = "agent-browser-"

const isAgentPartition = (partition: string) => partition.startsWith(AGENT_PARTITION_PREFIX)

export type WindowBrowserApi = {
  open: (partition: string, url: string) => Promise<BrowserViewState | undefined>
  setBounds: (partition: string, bounds: BrowserBounds | null) => Promise<void>
  setVisible: (partition: string, visible: boolean) => Promise<void>
  close: (partition: string) => Promise<void>
  navigate: (partition: string, action: "back" | "forward" | "reload") => Promise<void>
  setShared: (partition: string, shared: boolean) => Promise<void>
  getState: () => Promise<BrowserViewState[]>
  onUpdated: (cb: (state: BrowserViewState) => void) => () => void
  onClosed: (cb: (partition: string, epoch: number) => void) => () => void
}

export type BrowserBounds = { x: number; y: number; width: number; height: number }

export type BrowserViewState = {
  partition: string
  url: string
  title: string
  loading: boolean
  shared: boolean
  /** View generation from the main process: incremented on every
   * (re)creation of the partition's view. Optimistic client-only states
   * (fresh tabs) use 0 — real views always carry >= 1. */
  epoch: number
}

export function browserApi(): WindowBrowserApi | undefined {
  return window.api?.browser
}

function normalizeAddress(input: string) {
  const trimmed = input.trim()
  if (!trimmed) return undefined
  if (/^(https?|file):\/\//i.test(trimmed)) return trimmed
  // Local paths (absolute or ~-prefixed) are passed through raw — the main
  // process converts them to file:// URLs in controller.open().
  if (trimmed.startsWith("/") || trimmed.startsWith("~/")) return trimmed
  if (/^[\w-]+(\.[\w-]+)+(\/|$|:)/.test(trimmed)) return `https://${trimmed}`
  return `https://duckduckgo.com/?q=${encodeURIComponent(trimmed)}`
}

// Fresh tabs live on about:blank; show an empty address bar for it.
const displayUrl = (url: string) => (url === "about:blank" ? "" : url)

// Module-level monotonic counter: a panel remount (session → home → session,
// or HMR) must never reuse a partition id generated by a previous instance.
let tabSeq = 0

// External open requests (e.g. the file preview "open in embedded browser"
// button) travel over a window CustomEvent, not a module-level handler slot:
// an HMR update re-evaluates this module and would reset a module variable,
// permanently orphaning the live panel instance. Events are re-registered by
// whichever panel instance is mounted, so hot reloads self-heal.
const OPEN_TAB_EVENT = "browser-panel:open-tab"

/** Open a URL in a fresh user tab of the embedded browser panel. No-op when no panel is mounted. */
export function openInBrowserTab(url: string) {
  window.dispatchEvent(new CustomEvent(OPEN_TAB_EVENT, { detail: url }))
}

type BrowserTab = {
  partition: string
  agent: boolean
  state?: BrowserViewState
}

/**
 * Choose the next active partition after `closed` disappears from the strip.
 * Pure so the policy has exactly one definition (close paths and the
 * reconcile effect must agree): walk outward from the closed slot preferring
 * user tabs, then fall back to the last remaining tab (agent tabs beat an
 * empty strip), else "" when the strip is genuinely empty.
 */
export const pickFallback = (list: readonly BrowserTab[], closed: string): string => {
  const idx = list.findIndex((tab) => tab.partition === closed)
  const rest = list.filter((tab) => tab.partition !== closed)
  if (rest.length === 0) return ""
  for (let d = 0; d <= list.length; d++) {
    const before = list[idx - d]
    if (before && before.partition !== closed && !before.agent) return before.partition
    const after = list[idx + d]
    if (after && after.partition !== closed && !after.agent) return after.partition
  }
  return rest.at(-1)!.partition
}

/**
 * A state event for a partition the user closed is stale unless the main
 * process has since RE-CREATED the view (epoch strictly greater than the
 * closed view's). This one check replaces the old asymmetry — user
 * partitions blocked forever, agent partitions unblocked by loading=true —
 * because a genuinely recreated view is a real tab regardless of who
 * recreated it, and stale in-flight events can never carry a new epoch.
 */
const isStaleClosedEvent = (closedEpoch: number | undefined, next: BrowserViewState) =>
  closedEpoch !== undefined && next.epoch <= closedEpoch

export function BrowserPanel(props: { class?: string }) {
  const language = useLanguage()
  const { view } = useSessionLayout()
  const api = browserApi()

  const opened = createMemo(() => view().browser.opened())

  // All known views keyed by partition — the user tab plus any agent tabs.
  const [views, setViews] = createSignal<Record<string, BrowserViewState>>({})
  const [active, setActive] = createSignal(BROWSER_PARTITION)
  const [address, setAddress] = createSignal("")
  let placeholder: HTMLDivElement | undefined

  // User tabs are dynamic: every non-agent partition is a tab. The strip may
  // be empty (last tab closed) — the + button and the address bar both spawn
  // fresh tabs. Tabs render in first-seen order: Object.entries preserves
  // insertion order and setViews only ever appends new keys, so a freshly
  // created tab — user or agent — lands at the right edge of the strip.
  // (Grouping user tabs before agent tabs would shove every new user tab to
  // the LEFT of existing agent tabs.)
  const tabs = createMemo<BrowserTab[]>(() =>
    Object.entries(views()).map(([partition, state]) => ({
      partition,
      agent: isAgentPartition(partition),
      state,
    })),
  )
  const activeAgent = createMemo(() => isAgentPartition(active()))
  // Undefined when the strip is empty or the active tab is agent-owned —
  // every user-tab-scoped control (nav buttons, bounds, navigation) checks it.
  const activeUserTab = createMemo(() => {
    const tab = tabs().find((tab) => tab.partition === active())
    return tab && !tab.agent ? tab : undefined
  })

  // User-initiated navigations shown optimistically in the address bar.
  // Chromium reports the OLD url on did-start-loading (it only switches on
  // commit), so echoing every state event into the address bar would wipe it
  // back to the previous page the instant the user hits Enter. While a
  // user navigation is pending, the address bar is frozen until the new url
  // commits or the load ends.
  const pendingNavs = new Map<string, string>()

  // Partitions closed this run, mapped to the epoch of the view at close
  // time. A state event being in flight when its view is destroyed (emitted
  // just before teardown) would otherwise resurrect the tab in the strip;
  // only a strictly newer epoch (a genuinely re-created view) may unblock.
  const closedTabs = new Map<string, number>()

  // Single removal path for the mirror state: idempotent, used by the
  // optimistic close paths and by main-initiated teardowns (onClosed).
  const removeTab = (partition: string) => {
    pendingNavs.delete(partition)
    setViews((prev) => {
      if (!(partition in prev)) return prev
      const next = { ...prev }
      delete next[partition]
      return next
    })
  }

  const record = (next: BrowserViewState) => {
    const closedEpoch = closedTabs.get(next.partition)
    if (isStaleClosedEvent(closedEpoch, next)) return
    if (closedEpoch !== undefined) {
      // A view with a newer epoch than the closed one really exists again —
      // unblock the partition (agent re-navigated a closed tab, or a future
      // feature re-opened the same user partition).
      closedTabs.delete(next.partition)
    }
    const firstSighting = !(next.partition in views())
    setViews((prev) => ({ ...prev, [next.partition]: next }))
    // Agent started browsing while the panel is closed: slide the panel out
    // and follow the agent tab. Only on first sighting — a user who closes
    // the panel afterwards is not fighting repeated auto-opens.
    if (isAgentPartition(next.partition) && firstSighting && !opened()) {
      view().browser.open()
      setActive(next.partition)
      return
    }
    if (next.partition !== active()) return
    const pending = pendingNavs.get(next.partition)
    if (pending !== undefined) {
      if (!next.loading || next.url === pending) {
        pendingNavs.delete(next.partition)
        setAddress(displayUrl(next.url))
      }
      return
    }
    setAddress(displayUrl(next.url))
  }

  const syncBounds = () => {
    if (!api || !placeholder) return
    // With no active tab (empty strip) there is no view to mirror bounds
    // for — setBounds on an unknown partition would be a main-side no-op.
    if (!tabs().some((tab) => tab.partition === active() && tab.state)) return
    const rect = placeholder.getBoundingClientRect()
    if (rect.width < 2 || rect.height < 2) return
    void api.setBounds(active(), {
      x: rect.x,
      y: rect.y,
      width: rect.width,
      height: rect.height,
    })
  }

  onMount(() => {
    if (!api) return
    // External open requests land here: addUserTab creates the partition,
    // navigates, activates the tab and freezes the address bar pending commit.
    const handleOpenTab = (event: Event) => addUserTab((event as CustomEvent<string>).detail)
    window.addEventListener(OPEN_TAB_EVENT, handleOpenTab)
    onCleanup(() => {
      window.removeEventListener(OPEN_TAB_EVENT, handleOpenTab)
    })
    const ro = new ResizeObserver(syncBounds)
    ro.observe(placeholder!)
    window.addEventListener("resize", syncBounds)
    window.addEventListener("scroll", syncBounds, true)
    onCleanup(() => {
      ro.disconnect()
      window.removeEventListener("resize", syncBounds)
      window.removeEventListener("scroll", syncBounds, true)
      for (const partition of Object.keys(views())) {
        // Closed partitions are skipped: hiding them is pointless (their
        // views are already gone main-side) and the IPC would just log noise.
        if (closedTabs.has(partition)) continue
        void api.setVisible(partition, false)
        void api.setBounds(partition, null)
      }
    })

    const stop = api.onUpdated(record)
    if (stop) onCleanup(stop)

    // View teardowns from any source (user close, agent browser_close tool,
    // renderer crash, idle reap) remove the tab from the strip. Idempotent
    // with the optimistic removal in closeTab(); the close epoch recorded
    // here is authoritative — it blocks every stale in-flight event from the
    // destroyed generation.
    const stopClosed = api.onClosed((partition, epoch) => {
      closedTabs.set(partition, epoch)
      removeTab(partition)
    })
    if (stopClosed) onCleanup(stopClosed)

    void api.getState().then((states) => {
      setViews((prev) => {
        const next = { ...prev }
        for (const state of states) {
          // A tab closed while this snapshot was in flight must not come
          // back: only a strictly newer epoch (view re-created after the
          // close) may pass the closed-partition guard.
          if (isStaleClosedEvent(closedTabs.get(state.partition), state)) continue
          // record() events are always fresher than the snapshot — only
          // fill partitions the event stream has not touched yet.
          if (state.partition in prev) continue
          next[state.partition] = state
        }
        return next
      })
      const current = states.find((state) => state.partition === active())
      if (current && !closedTabs.has(active()) && !pendingNavs.has(active())) {
        setAddress(displayUrl(current.url))
      }
      // Agent already mid-browse at mount (e.g. renderer reloaded while the
      // agent kept working): slide the panel out to follow it. Stale idle
      // views from earlier sessions do not trigger this.
      const busy = states.find((state) => isAgentPartition(state.partition) && state.loading)
      if (busy && !opened()) {
        view().browser.open()
        setActive(busy.partition)
      }
    })
  })

  // Visibility follows panel state + active tab: exactly one partition is
  // shown, bounds are retained main-side so tab switches re-show in place.
  createEffect(() => {
    if (!api) return
    const open = opened()
    const current = active()
    for (const tab of tabs()) {
      // Defensive: a tab without main-process state has no view behind it —
      // setVisible would ensure-create one nobody drives.
      if (!tab.state) continue
      void api.setVisible(tab.partition, open && tab.partition === current)
    }
    if (open) queueMicrotask(syncBounds)
  })

  // Reset the address bar when the active tab changes (untracked views read —
  // background updates to other tabs must not clobber in-progress typing;
  // live updates for the active tab arrive via record()). A pending user
  // navigation wins: switching away and back mid-load must restore the
  // optimistic target, not the pre-navigation url.
  createEffect(() => {
    const partition = active()
    setAddress(displayUrl(untrack(() => pendingNavs.get(partition) ?? views()[partition]?.url ?? "")))
  })

  const go = (raw: string) => {
    if (!api || !raw.trim()) return
    if (activeAgent()) return // agent tabs are read-only; the agent drives them
    // Empty strip: typing an address spawns a tab for it, like a fresh tab.
    if (!activeUserTab()) {
      addUserTab(raw)
      return
    }
    const partition = active()
    const url = normalizeAddress(raw)
    if (!url) return
    // Optimistic: show the target address right away and freeze it there
    // until the navigation commits (see pendingNavs in record()).
    pendingNavs.set(partition, url)
    setAddress(url)
    void api
      .open(partition, url)
      .then((next) => {
        pendingNavs.delete(partition)
        if (next && active() === partition) setAddress(displayUrl(next.url))
      })
      .catch(() => {
        // Navigation failed (bad host, CDP error): unfreeze the address bar
        // and leave what the user typed.
        pendingNavs.delete(partition)
      })
  }

  const addUserTab = (url?: string) => {
    if (!api) return
    // Fresh persistent partition per tab: cookies/storage survive app
    // restarts, and the view is recreated on demand by the main process.
    tabSeq += 1
    const partition = `persist:tab-${Date.now().toString(36)}-${tabSeq}`
    const blank: BrowserViewState = { partition, url: "", title: "", loading: false, shared: false, epoch: 0 }
    setViews((prev) => ({ ...prev, [partition]: blank }))
    setActive(partition)
    const target = url ? normalizeAddress(url) : undefined
    pendingNavs.delete(partition)
    if (target) {
      pendingNavs.set(partition, target)
      setAddress(target)
    } else {
      setAddress("")
    }
    void api.open(partition, target ?? "about:blank").then(
      (next) => {
        pendingNavs.delete(partition)
        // Re-assert visibility: the visibility effect runs synchronously on
        // the optimistic state and its setVisible(true) may reach the main
        // process before open()'s ensure has created the view (where it is
        // now a deliberate no-op). Any state event would also re-trigger the
        // effect, but an instant page (about:blank) must not depend on that.
        void api.setVisible(partition, opened())
        if (next && active() === partition) setAddress(next.url === "about:blank" ? "" : next.url)
      },
      () => {
        pendingNavs.delete(partition)
      },
    )
  }

  /**
   * Unified close path (user tabs and agent tabs — the strip-level effects
   * are identical): fire the close IPC, block stale events by the last epoch
   * we saw (the authoritative close epoch arrives via onClosed), remove the
   * tab, and pick the next active tab through the single fallback policy.
   * The agent-tab confirmation capsule stays a call-site concern.
   */
  const closeTab = (partition: string) => {
    if (!api) return
    void api.close(partition)
    closedTabs.set(partition, views()[partition]?.epoch ?? 0)
    removeTab(partition)
    if (active() === partition) setActive(pickFallback(tabs(), partition))
  }

  const closeUserTab = closeTab

  // Agent tabs can be closed by the user too, behind a confirmation capsule:
  // agents often leave views open and idle, wasting resources. If the agent
  // genuinely still needs the tab it simply navigates again — the view is
  // re-created with a new epoch and record() unblocks the partition.
  const closeAgentTab = (partition: string) => {
    closeTab(partition)
    setConfirmClose(undefined)
  }

  const [confirmClose, setConfirmClose] = createSignal<string>()
  let capsuleRef: HTMLDivElement | undefined
  // Dismiss the capsule on Escape or any pointer press outside of it.
  createEffect(() => {
    if (!confirmClose()) return
    const dismiss = (e: PointerEvent) => {
      if (capsuleRef?.contains(e.target as Node)) return
      setConfirmClose(undefined)
    }
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setConfirmClose(undefined)
    }
    window.addEventListener("pointerdown", dismiss, true)
    window.addEventListener("keydown", onKey)
    onCleanup(() => {
      window.removeEventListener("pointerdown", dismiss, true)
      window.removeEventListener("keydown", onKey)
    })
  })

  // Reconcile: active() must always point at an existing tab, or be "" only
  // while the strip is truly empty — a dangling value (a partition that
  // vanished across a reload race) would leave no highlighted tab and hide
  // every view, and a sticky "" would keep tabs unhighlighted after restore.
  // Uses the same pickFallback policy as the close paths, so active-fallback
  // behavior has exactly one definition.
  createEffect(() => {
    const list = tabs()
    const current = active()
    if (current !== "" && list.some((tab) => tab.partition === current)) return
    if (current === "" && list.length === 0) return
    setActive(pickFallback(list, current))
  })

  const tabLabel = (tab: BrowserTab) => {
    // Interstitial pages (e.g. Google /sorry) expose their URL as the title —
    // fall back to the hostname so the tab never shows a raw URL. Chromium's
    // about:blank page literally titles itself "about:blank" — treat that as
    // empty so the blank tab shows the static label.
    const title = tab.state?.title?.trim()
    if (title && title !== "about:blank" && !/^https?:\/\//i.test(title)) return title
    try {
      const parsed = new URL(tab.state?.url ?? "")
      // file:// URLs have no hostname — show the file name instead.
      if (parsed.protocol === "file:") {
        const name = decodeURIComponent(parsed.pathname.split("/").filter(Boolean).pop() ?? "")
        if (name) return name
      }
      if (parsed.hostname && parsed.hostname !== "about:blank") return parsed.hostname
    } catch {
      // not a URL — fall through to the static label
    }
    return tab.agent ? language.t("panel.browser.agentTab") : language.t("panel.browser.tab")
  }

  return (
    <Show when={api}>
      <div
        id="browser-panel"
        role="region"
        aria-label={language.t("command.browser.toggle")}
        aria-hidden={!opened()}
        inert={!opened()}
        class={props.class}
        classList={{
          "relative size-full min-w-0 flex flex-col overflow-hidden bg-background-stronger": true,
          "pointer-events-none": !opened(),
        }}
      >
        <div class="flex flex-col flex-1 min-h-0">
          <div class="relative flex h-7 shrink-0 items-center gap-1 px-2 border-b border-border-weaker-base">
            {/* Agent-tab close confirmation capsule. Must live in the tab-strip
                row: the native WebContentsView always paints ABOVE the DOM, so
                any overlay inside the placeholder container (the region the
                view mirrors) is invisible behind the web page. The strip row is
                the only DOM-only band of the panel. */}
            <Show when={confirmClose()} keyed>
              {(partition) => (
                <div
                  ref={capsuleRef}
                  class="absolute left-1/2 top-1/2 z-10 flex max-w-[calc(100%-8px)] -translate-x-1/2 -translate-y-1/2 items-center gap-2 whitespace-nowrap rounded-full border border-border-weak-base bg-surface-inset-base py-0.5 pl-3 pr-1 text-12-regular shadow-md"
                >
                  <span class="truncate text-text-strong">
                    {language.t("panel.browser.closeAgentConfirm")}
                  </span>
                  <button
                    type="button"
                    onClick={() => closeAgentTab(partition)}
                    class="shrink-0 rounded-full border border-border-weak-base bg-surface-base px-2.5 py-0.5 text-text-strong transition-colors hover:bg-surface-inset-base"
                  >
                    {language.t("panel.browser.closeAction")}
                  </button>
                  <button
                    type="button"
                    onClick={() => setConfirmClose(undefined)}
                    class="shrink-0 rounded-full px-2 py-0.5 text-text-weak transition-colors hover:text-text-strong"
                  >
                    {language.t("common.cancel")}
                  </button>
                </div>
              )}
            </Show>
            {/* Index (not For): tabs() re-maps Object.entries into fresh
                objects on every state event, and For diffs by reference —
                it would tear down and rebuild every tab button (a click can
                straddle mousedown/mouseup across nodes mid-load). Index
                reuses DOM by position and re-runs the reactive expressions. */}
            <Index each={tabs()}>
              {(tab) => (
                <button
                  type="button"
                  onClick={() => setActive(tab().partition)}
                  onAuxClick={(e) => {
                    if (e.button !== 1) return
                    if (tab().agent) setConfirmClose(tab().partition)
                    else closeUserTab(tab().partition)
                  }}
                  title={
                    tab().agent
                      ? `${language.t("panel.browser.agentTab")} · ${tab().state?.url ?? ""}`
                      : tab().state?.url
                  }
                  class="group/tab flex h-6 min-w-0 max-w-56 cursor-pointer select-none items-center gap-1.5 rounded-md pl-2 text-12-regular outline-none transition-[background-color,color,transform] duration-150 active:scale-[0.97] focus-visible:ring-1 focus-visible:ring-border-strong-base"
                  classList={{
                    "pr-2": tab().agent,
                    "pr-1": !tab().agent,
                    "bg-surface-inset-base": active() === tab().partition && !tab().agent,
                    "text-text-strong": active() === tab().partition,
                    "text-text-weak hover:bg-surface-inset-base hover:text-text-strong":
                      active() !== tab().partition,
                  }}
                  style={
                    tab().agent
                      ? {
                          color: "var(--surface-brand-base)",
                          "background-color":
                            active() === tab().partition
                              ? "color-mix(in srgb, var(--surface-brand-base) 14%, transparent)"
                              : undefined,
                        }
                      : undefined
                  }
                >
                  {/* Leading slot: a spinner while the page loads (tab-level
                      loading feedback), otherwise the brand dot for agent tabs.
                      A fresh empty tab only loads about:blank — nothing worth
                      waiting for, and a spinner flash there reads as jitter. */}
                  <Show
                    when={
                      tab().state?.loading === true &&
                      tab().state?.url !== "about:blank" &&
                      tab().state?.url !== ""
                    }
                    fallback={
                      <Show when={tab().agent}>
                        <span
                          class="h-1.5 w-1.5 shrink-0 rounded-full"
                          style={{ "background-color": "var(--surface-brand-base)" }}
                        />
                      </Show>
                    }
                  >
                    <Spinner
                      class="size-3 shrink-0"
                      style={tab().agent ? { color: "var(--surface-brand-base)" } : undefined}
                    />
                  </Show>
                  <span class="truncate">{tabLabel(tab())}</span>
                  <span
                    role="button"
                    aria-label={language.t("panel.browser.closeTab")}
                    title={language.t("panel.browser.closeTab")}
                    onClick={(e) => {
                      e.stopPropagation()
                      if (tab().agent) setConfirmClose(tab().partition)
                      else closeUserTab(tab().partition)
                    }}
                    class="flex h-4 w-4 shrink-0 cursor-pointer items-center justify-center rounded-sm text-text-weak transition-[opacity,background-color,color,transform] duration-100 hover:bg-background-base hover:text-text-strong active:scale-90"
                    classList={{
                      "opacity-0 group-hover/tab:opacity-100": active() !== tab().partition,
                    }}
                  >
                    <Icon name="close-small" size="small" />
                  </span>
                </button>
              )}
            </Index>
            <IconButton
              icon="plus-small"
              variant="ghost"
              class="h-5 w-5 shrink-0"
              onClick={() => addUserTab()}
              aria-label={language.t("panel.browser.newTab")}
            />
          </div>
          <div class="h-10 shrink-0 flex items-center gap-1 px-2 border-b border-border-weaker-base bg-background-stronger">
            <IconButton
              icon="arrow-left"
              variant="ghost"
              disabled={!activeUserTab()}
              onClick={() => activeUserTab() && void api!.navigate(active(), "back")}
              aria-label={language.t("panel.browser.back")}
            />
            <IconButton
              icon="arrow-right"
              variant="ghost"
              disabled={!activeUserTab()}
              onClick={() => activeUserTab() && void api!.navigate(active(), "forward")}
              aria-label={language.t("panel.browser.forward")}
            />
            <IconButton
              icon="refresh-small"
              variant="ghost"
              disabled={!activeUserTab()}
              onClick={() => activeUserTab() && void api!.navigate(active(), "reload")}
              aria-label={language.t("panel.browser.reload")}
            />
            <input
              type="text"
              value={address()}
              readonly={activeAgent()}
              onInput={(e) => setAddress(e.currentTarget.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") go(e.currentTarget.value)
              }}
              placeholder={language.t("panel.browser.addressPlaceholder")}
              spellcheck={false}
              autocomplete="off"
              class="flex-1 min-w-0 h-7 px-2 rounded-md bg-surface-base text-13-regular text-text-strong placeholder:text-text-weak outline-none focus:ring-1 focus:ring-border-strong-base"
              classList={{ "text-text-weak": activeAgent() }}
            />
            <IconButton
              icon="close-small"
              variant="ghost"
              onClick={() => view().browser.close()}
              aria-label={language.t("common.close")}
            />
          </div>
          <div class="flex-1 min-h-0 relative">
            <div ref={placeholder} class="absolute inset-0" data-browser-placeholder={active()} />
            <Show when={tabs().length === 0}>
              <div class="absolute inset-0 flex items-center justify-center text-13-regular text-text-weak pointer-events-none">
                {language.t("panel.browser.empty")}
              </div>
            </Show>
          </div>
        </div>
      </div>
    </Show>
  )
}
